[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@foundry-devops/=lib/foundry-devops/contracts",
]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
